on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    # container: sandrolex2/gh-runner:ubuntu-builder-no-docker
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: sandro-lex-form3/actions-tools2@main
        with:
          who-to-greet: 'vic-viper'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash